// Generated by CoffeeScript 1.9.2
(function() {
  define(['Ethan'], function(Ethan) {
    Ethan.makeCalendar(Ethan.calendarTypes.avgTip);
    Ethan.makeCalendar(Ethan.calendarTypes.totalFare);
  });

}).call(this);
