// Generated by CoffeeScript 1.9.2
(function() {
  define(['calendarViz'], function(CalendarViz) {
    CalendarViz.makeCalendar(CalendarViz.calendarTypes.avgTip);
    CalendarViz.makeCalendar(CalendarViz.calendarTypes.totalFare);
  });

}).call(this);
