// Generated by CoffeeScript 1.9.2
(function() {
  define(['jquery', 'd3'], function($, d3) {
    var calendarTypes, holyshit;
    Number.prototype.formatMoney = function(t, d, c) {
      var i, j, n, s;
      if (t == null) {
        t = ',';
      }
      if (d == null) {
        d = '.';
      }
      if (c == null) {
        c = '$';
      }
      n = this;
      s = n < 0 ? "-" + c : c;
      i = Math.abs(n).toFixed(2);
      j = ((j = i.length) > 3 ? j % 3 : 0);
      if (j) {
        s += i.substr(0, j) + t;
      }
      return s + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + t);
    };
    calendarTypes = {
      avgTip: {
        field: 'avgTip',
        format: function(x) {
          return "$" + (parseFloat(x).toFixed(2));
        },
        domain: [2, 3],
        container: "#calendar"
      },
      totalFare: {
        field: 'totalFare',
        format: function(x) {
          return "" + (parseInt(x));
        },
        domain: [1000000, 8000000],
        container: "#fare"
      }
    };
    holyshit = function(calendarType) {
      var cellSize, color, day, format, height, monthPath, percent, rect, svg, week, width;
      width = 903;
      height = 136;
      cellSize = 17;
      day = d3.time.format('%w');
      week = d3.time.format('%U');
      percent = d3.format('.1%');
      format = d3.time.format('%Y-%m-%d');
      color = d3.scale.quantize().domain(calendarType.domain).range(d3.range(11).map(function(d) {
        return 'q' + d + '-11';
      }));
      svg = d3.select(calendarType.container).selectAll('svg').data(d3.range(2013, 2014)).enter().append('svg').attr('width', width).attr('height', height).attr('class', 'RdYlGn').append('g').attr('transform', 'translate(' + (width - (cellSize * 53)) / 2 + ',' + height - (cellSize * 7) - 1 + ')');
      monthPath = function(t0) {
        var d0, d1, t1, w0, w1;
        t1 = new Date(t0.getFullYear(), t0.getMonth() + 1, 0);
        d0 = +day(t0);
        w0 = +week(t0);
        d1 = +day(t1);
        w1 = +week(t1);
        return 'M' + (w0 + 1) * cellSize + ',' + d0 * cellSize + 'H' + w0 * cellSize + 'V' + 7 * cellSize + 'H' + w1 * cellSize + 'V' + (d1 + 1) * cellSize + 'H' + (w1 + 1) * cellSize + 'V' + 0 + 'H' + (w0 + 1) * cellSize + 'Z';
      };
      svg.append('text').attr('transform', 'translate(-6,' + cellSize * 3.5 + ')rotate(-90)').style('text-anchor', 'middle').text(function(d) {
        return d;
      });
      rect = svg.selectAll('.day').data(function(d) {
        return d3.time.days(new Date(d, 0, 1), new Date(d + 1, 0, 1));
      }).enter().append('rect').attr('class', 'day').attr('width', cellSize).attr('height', cellSize).attr('x', function(d) {
        return week(d) * cellSize;
      }).attr('y', function(d) {
        return day(d) * cellSize;
      }).datum(format);
      rect.append('title').text(function(d) {
        return d;
      });
      svg.selectAll('.month').data(function(d) {
        return d3.time.months(new Date(d, 0, 1), new Date(d + 1, 0, 1));
      }).enter().append('path').attr('class', 'month').attr('d', monthPath);
      d3.csv('data/onlyCCand5To500.csv', function(error, csv) {
        var data;
        data = d3.nest().key(function(d) {
          return d.datetime;
        }).rollup(function(d) {
          return parseFloat(d[0][calendarType.field]);
        }).map(csv);
        rect.filter(function(d) {
          return d in data;
        }).attr('class', function(d) {
          return 'day ' + color(data[d]);
        }).select('title').text(function(d) {
          return d + ': ' + calendarType.format(data[d]);
        });
      });
      return d3.select(self.frameElement).style('height', '2910px');
    };
    return {
      makeCalendar: holyshit,
      calendarTypes: calendarTypes
    };
  });

}).call(this);
