// Generated by CoffeeScript 1.9.2
(function() {
  require({
    baseUrl: '/cabbie_stats/js/',
    paths: {
      jquery: '../node_modules/jquery/dist/jquery.min',
      react: '../node_modules/react/dist/react',
      text: '../node_modules/text/text',
      crypto: '../node_modules/crypto/md5',
      CabbieStats: 'cabbie',
      cabbieData: '../data/cabbies_obj.json',
      extremeData: '../data/extremes.json',
      infoData: '../data/info.json'
    }
  });

}).call(this);
